version: "3.8"

services:
  dev:
    container_name: app-dev
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
  prod:
    container_name: app-prod
    image: app-prod
    build:
      context: .
      target: production